name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build and test chsarp:
    name: Build and test chsarp
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build .NET project
      run: dotnet build
  
    - name : run Tests in parent folder 
      run: dotnet test
      
  build and test typescript:
    name: Build and test typescript
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: install NPM related depedencies
      working-directory: DotnetTemplate.Web 
      run: npm install

    - name: Build Web DotnetTemplate
      working-directory: DotnetTemplate.Web 
      run: npm run build 

    - name: Run NPM related tests
      working-directory: DotnetTemplate.Web 
      run: npm t

    - name: Run Lint checks 
      working-directory: DotnetTemplate.Web 
      run: npm run lint


    

    
